name: GitHub Actions Vercel Preview Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token='DN04hhgqqBaK8hoN1IzQmb7Kb06qGvp3'
      - name: Build Project Artifacts
        run: vercel build --token='DN04hhgqqBaK8hoN1IzQmb7Kb06qGvp3'
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token='DN04hhgqqBaK8hoN1IzQmb7Kb06qGvp3'